[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_cloud_funding = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# ここに自分の開発用のwalletの場所を指定
wallet = "/Users/ishikawatakeshi/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
